'use strict';
// These tests are deliberately unable to connect to a production Firebase project.
const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {initializeApp,deleteApp}=require('firebase-admin/app');
const {getFirestore}=require('firebase-admin/firestore');
const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,updateDoc}=require('firebase/firestore');
const {makeBillingService}=require('../billing');
const {makeLifecycleService}=require('../lifecycle');
const {makeMailService}=require('../mail');
const {makePaymentService}=require('../payments');
const {renderInvoice}=require('../pdf');
const {sha256}=require('../domain');
assert.match(process.env.FIRESTORE_EMULATOR_HOST||'',/^(127\.0\.0\.1|localhost):\d+$/,'Start the local emulator first.');
const projectId='demo-songkeep-invoices';
const app=initializeApp({projectId},'integration');const db=getFirestore(app);
const staff={uid:'staff',email:'staff@example.com',emailVerified:true};const buyer={uid:'buyer',email:'buyer@example.com',emailVerified:true};const guest={uid:'outsider',email:'outsider@example.com',emailVerified:true};const recipient={uid:'person',email:'person@example.com',emailVerified:true};
let environment,clock=new Date('2026-01-01T12:00:00.000Z');
const objects=new Map();const bucket={file:path=>({exists:async()=>[objects.has(path)],download:async()=>[objects.get(path)],save:async(bytes)=>{if(objects.has(path))throw Object.assign(new Error('exists'),{code:412});objects.set(path,bytes);}})};
const billing=makeBillingService(db,{now:()=>clock,renderPdf:renderInvoice,bucket});const lifecycle=makeLifecycleService(db);
const config={legalName:'Example SongKeep Company — TEST ONLY',dba:'SongKeep demonstration',address:'123 Example Avenue\nExample City, VA 00000',email:'billing@example.com',phone:'555-0100',paymentInstructions:'Demonstration only. Do not pay this sample invoice.',terms:'Test service and cancellation terms; no real charge.',dueDays:14,taxBasisPoints:0,taxNote:'Sample tax treatment, not a tax determination.',taxReviewed:true,appUrl:'https://example.com',autoIssue:true};
let counter=0;const requestInput=(extra={})=>({organizationId:'org',offeringId:'honor-a-life-song-experience',preferredStartsAt:'2026-10-10T12:00:00.000Z',requestedPaymentMethod:'invoice',agreementAcknowledged:true,idempotencyKey:`request-${++counter}`,venue:'Example Community Hall',participantEstimate:10,...extra});
async function draft(extra={}){return billing.createRequest(buyer,requestInput(extra));}const args=r=>({organizationId:'org',invoiceId:r.id});async function issued(extra={}){const r=await draft(extra);return billing.issue(staff,args(r));}
const pay=(i,amountCents,reference)=>billing.recordPayment(staff,{...args(i),amountCents,method:'check',reference,confirmed:true});
const path='organizations/org/experiences/event';
async function seedRecipient(){
  const previous=await db.collection(`${path}/participants/person/consents`).get();for(const consent of previous.docs)await consent.ref.delete();
  await db.doc(path).set({organizationId:'org',status:'post_event'});
  await db.doc(`${path}/participants/person`).set({name:'Sample participant',permissionVersion:1,currentConsentId:'consent'});
  await db.doc(`${path}/participants/person/consents/consent`).set({version:1,state:'active',scopes:['participation','internal_creative_use','designated_family_sharing','private_performance'],participantDeliveryEmail:'person@example.com',designatedFamilyEmails:['family@example.com']});
  await db.doc(`${path}/accessInvitations/access`).set({status:'accepted',acceptedBy:'person',recipientEmail:'person@example.com',participantId:'person',recipient:'participant',entitlementIds:['song-entitlement']});
  await db.doc(`${path}/entitlements/song-entitlement`).set({organizationId:'org',experienceId:'event',participantId:'person',audience:'participant',consentRecordId:'consent',requiredConsentScopes:['participation'],authorizedRecipientEmails:['person@example.com'],status:'active',assetId:'song'});
  await db.doc('organizations/org/assets/song').set({organizationId:'org',experienceId:'event',participantId:'person',kind:'song',title:'Sample song',status:'ready',workflowStatus:'released',organizationVisible:true,assignmentId:'assignment',storagePath:'organizations/org/creator-submissions/assignment/song/song.mp3'});
  await db.doc('users/person').set({email:'person@example.com'});
  await db.doc('users/person/experienceAccess/access').set({organizationId:'org',organizationName:'Example Community',experienceId:'event',experienceTitle:'Example event',participantId:'person',participantName:'Sample participant',recipient:'participant',entitlementIds:['song-entitlement']});
  for(const [productId,kind] of [['digital','digital_song'],['video','event_video'],['photos','photo_music_package']])await db.doc(`postExperienceProducts/${productId}`).set({status:'active',audiences:['participant'],kind,name:'Sample keepsake',priceCents:2000});
}
before(async()=>{
  environment=await initializeTestEnvironment({projectId,firestore:{host:process.env.FIRESTORE_EMULATOR_HOST.split(':')[0],port:Number(process.env.FIRESTORE_EMULATOR_HOST.split(':')[1]),rules:fs.readFileSync(require('node:path').resolve(__dirname,'../../firestore.rules'),'utf8')}});
  await environment.clearFirestore();await db.doc('admins/staff').set({active:true});
  await db.doc('organizations/org').set({name:'Example Community',address:'456 Sample Street',billingProfile:{name:'Example Community',contactName:'Alex Rivera',email:'buyer@example.com',address:'456 Sample Street',purchaseOrder:'EXAMPLE-PO'}});
  await db.doc('organizations/org/members/buyer').set({userId:'buyer',status:'active',role:'organization_admin',displayName:'Alex Rivera',email:'buyer@example.com'});
  await db.doc('organizations/org/members/viewer').set({userId:'viewer',status:'active',role:'viewer'});
});
after(async()=>{await environment?.cleanup();await db.terminate();await deleteApp(app);});
test('unconfigured invoicing preserves the draft without inventing legal/tax information',async()=>{const r=await draft();await assert.rejects(()=>billing.issue(staff,args(r)),/legal business/);assert.equal((await billing.read(buyer,args(r))).status,'draft');await assert.rejects(()=>billing.configure(staff,{...config,taxReviewed:false}),/tax treatment/);await billing.configure(staff,config);});
test('catalog and tenant authority are server controlled',async()=>{await assert.rejects(()=>billing.createRequest(guest,requestInput()),/permission/);await assert.rejects(()=>billing.createRequest({uid:'viewer'},requestInput()),/permission/);await assert.rejects(()=>billing.createRequest(buyer,requestInput({offeringId:'invented'})),/available/);const r=await draft({amountCents:1});assert.equal(r.amountCents,250000);await assert.rejects(()=>billing.read(guest,args(r)),/permission/);});
test('repeated requests are idempotent and mismatched retry payloads are rejected',async()=>{const input=requestInput();const [a,b]=await Promise.all([billing.createRequest(buyer,input),billing.createRequest(buyer,input)]);assert.equal(a.id,b.id);await assert.rejects(()=>billing.createRequest(buyer,{...input,venue:'Different venue'}),/already in use/);});
test('concurrent invoice issue allocates one number per invoice and unique numbers across invoices',async()=>{const r=await draft();const results=await Promise.all([billing.issue(staff,args(r)),billing.issue(staff,args(r))]);assert.equal(results[0].invoiceNumber,results[1].invoiceNumber);const next=await Promise.all([issued(),issued(),issued()]);assert.equal(new Set(next.map(i=>i.invoiceNumber)).size,3);});
test('issued snapshots and generated PDF bytes do not change with seller or buyer edits',async()=>{const i=await issued();const first=await billing.download(buyer,args(i));const bytes=Buffer.from(first.pdfBase64,'base64');assert.equal(bytes.subarray(0,4).toString(),'%PDF');assert.equal(sha256(bytes),first.sha256);await billing.configure(staff,{...config,legalName:'Changed seller TEST ONLY'});const again=await billing.issue(staff,{...args(i),discountCents:100});assert.deepEqual(again.commercial,i.commercial);assert.equal((await billing.download(buyer,args(i))).sha256,first.sha256);await billing.configure(staff,config);if(process.env.SONGKEEP_TEST_PDF)fs.writeFileSync(process.env.SONGKEEP_TEST_PDF,bytes);});
test('partial payment and duplicate final confirmation create exactly one experience',async()=>{const i=await issued();const first=await pay(i,50000,'PARTIAL-CHECK');assert.equal(first.experienceId,null);assert.equal((await billing.read(buyer,args(i))).amountDueCents,200000);const results=await Promise.all([pay(i,200000,'FINAL-CHECK'),pay(i,200000,'FINAL-CHECK')]);assert.equal(results.filter(x=>x.duplicate).length,1);const stored=await billing.read(buyer,args(i));assert.equal(stored.status,'paid');assert.equal(stored.amountDueCents,0);assert.equal((await db.collection('organizations/org/experiences').where('sourceExperienceRequestId','==',i.requestId).get()).size,1);assert.equal((await db.doc(`organizations/org/experienceRequests/${i.requestId}`).get()).data().nurtureTrack,'customer_onboarding');await assert.rejects(()=>pay(i,1,'OVERPAY'),/another payment/);});
test('manual reconciliation needs staff authority, actual funds confirmation and a unique reference',async()=>{const i=await issued();await assert.rejects(()=>billing.recordPayment(buyer,{...args(i),amountCents:250000,method:'check',reference:'NO',confirmed:true}),/staff/);await assert.rejects(()=>billing.recordPayment(staff,{...args(i),amountCents:250000,method:'check',reference:'NO'}),/funds/);await assert.rejects(()=>pay(i,200000,'FINAL-CHECK'),/another amount or invoice/);await assert.rejects(()=>pay(i,250001,'TOO-MUCH'),/exceeds/);});
test('package replacement cancels only the unpaid request, invoice, order and queued reminders atomically',async()=>{const old=await issued();const replacement=await draft({offeringId:'songkeep-legacy-album',replacesRequestId:old.requestId});assert.equal((await billing.read(buyer,args(old))).status,'void');assert.equal((await db.doc(`organizations/org/orders/${old.orderId}`).get()).data().status,'void');assert.equal((await db.doc(`organizations/org/experienceRequests/${old.requestId}`).get()).data().replacedByRequestId,replacement.id);assert.equal((await db.doc(`organizations/org/invoices/${old.id}/invoiceMessages/issued-v1`).get()).data().status,'cancelled');await assert.rejects(()=>draft({replacesRequestId:old.requestId}),/Only an open/);});
test('concurrent replacements leave only one active successor',async()=>{const old=await issued();const result=await Promise.allSettled([draft({replacesRequestId:old.requestId}),draft({offeringId:'songkeep-legacy-album',replacesRequestId:old.requestId})]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);});
test('paid and in-flight-checkout invoices cannot be changed or manually collected twice',async()=>{const i=await issued();await db.doc(`organizations/org/invoices/${i.id}`).update({checkout:{status:'open',sessionId:'cs_test',amountCents:250000,expiresAt:'2000-01-01'}});await assert.rejects(()=>draft({replacesRequestId:i.requestId}),/pending checkout/);await assert.rejects(()=>pay(i,250000,'DUPLICATE-CARD'),/online payment/);await assert.rejects(()=>billing.close(staff,{...args(i),action:'void',reason:'test'}),/active checkout/);await assert.rejects(()=>billing.recordPayment({uid:'webhook'},{...args(i),amountCents:1,currency:'usd',sessionId:'cs_wrong',reference:'pi_wrong'},true),/does not match/);});
test('legacy external invoices cannot be overwritten without staff reconciliation evidence',async()=>{await db.doc('organizations/org/experienceRequests/legacy').set({offeringId:'single-song-group-event',amountCents:20000,status:'invoice_open',financialStatus:'invoice_open',invoiceUrl:'https://example.com/old-invoice',createdByUserId:'buyer'});await assert.rejects(()=>billing.prepare(buyer,{organizationId:'org',requestId:'legacy'}),/external invoice/);await billing.prepare(staff,{organizationId:'org',requestId:'legacy',confirmExternalReplacement:true,reason:'External invoice void verified TEST'});assert.equal((await billing.read(buyer,{organizationId:'org',invoiceId:'legacy'})).status,'draft');});
test('reminders are idempotent and suppressed after confirmed payment',async()=>{const i=await issued();clock=new Date('2026-01-16T12:00:00Z');await billing.reminders();await billing.reminders();const ref=db.doc(`organizations/org/invoices/${i.id}`);assert.equal((await ref.collection('invoiceMessages').where('kind','==','overdue').get()).size,1);await pay(i,250000,'REMINDER-PAID');await billing.reminders();assert.equal((await ref.collection('invoiceMessages').where('status','==','queued').get()).docs.some(d=>d.data().kind==='overdue'),false);assert.equal((await db.doc(`billingFollowUp/org-${i.id}`).get()).data().status,'resolved');clock=new Date('2026-01-01T12:00:00Z');});
test('email sent state requires provider acceptance and retry preserves provider idempotency',async()=>{const i=await issued();const ref=db.doc(`organizations/org/invoices/${i.id}/invoiceMessages/issued-v1`);let calls=0;const failed=makeMailService(db,async()=>{calls++;throw Error('offline');});await failed.deliver(ref);assert.equal((await ref.get()).data().status,'retry');assert.equal((await billing.read(buyer,args(i))).sentAt,undefined);await ref.update({retryAt:new Date(0)});const good=makeMailService(db,async input=>{calls++;assert.match(input.idempotencyKey,/songkeep-/);return {id:'mail_test'};});await good.deliver(ref);await good.deliver(ref);assert.equal(calls,2);assert.equal((await ref.get()).data().status,'sent');});
test('recorded refunds preserve original commercial total, payment evidence and stop reminders',async()=>{const i=await issued();await pay(i,250000,'REFUND-CHECK');await billing.recordRefund(staff,{...args(i),amountCents:50000,reference:'REFUND-1',reason:'Test adjustment',confirmed:true});const partial=await billing.read(buyer,args(i));assert.equal(partial.commercial.totalCents,250000);assert.equal(partial.amountPaidCents,250000);assert.equal(partial.amountRefundedCents,50000);assert.equal(partial.remindersPaused,true);await billing.recordRefund(staff,{...args(i),amountCents:200000,reference:'REFUND-2',reason:'Test cancellation',confirmed:true});assert.equal((await billing.read(buyer,args(i))).status,'refunded');});
test('Stripe session creation is recoverable and the browser return alone has no payment authority',async()=>{const i=await issued();const sessions=new Map();let creations=0;const stripe={checkout:{sessions:{create:async(input,{idempotencyKey})=>{if(!sessions.has(idempotencyKey)){creations++;sessions.set(idempotencyKey,{id:'cs_verified',url:'https://checkout.stripe.com/test',status:'open',payment_status:'unpaid',mode:'payment',metadata:input.metadata,amount_total:250000,currency:'usd',payment_intent:'pi_verified',expires_at:1800000000});}return sessions.get(idempotencyKey);},retrieve:async()=>[...sessions.values()][0]}}};const service=makePaymentService(db,stripe,billing);await service.checkout(buyer,args(i));await service.checkout(buyer,args(i));assert.equal(creations,1);assert.notEqual((await billing.read(buyer,args(i))).status,'paid');const session=[...sessions.values()][0];session.payment_status='paid';session.status='complete';await service.webhook({id:'evt_verified',type:'checkout.session.completed',data:{object:session}});await service.webhook({id:'evt_verified',type:'checkout.session.completed',data:{object:session}});assert.equal((await billing.read(buyer,args(i))).status,'paid');});
test('family recipient validation fails before the permission response becomes submitted',async()=>{await seedRecipient();await db.doc(`${path}/permissionInvitations/permission`).set({status:'pending',participantId:'person',recipientEmail:recipient.email});const input={organizationId:'org',experienceId:'event',invitationId:'permission',signatureName:'Sample participant',authorityBasis:'self',scopes:['participation','internal_creative_use','designated_family_sharing'],designatedFamilyEmails:[]};await assert.rejects(()=>lifecycle.submitPermission(recipient,input),/family email/);assert.equal((await db.doc(`${path}/permissionInvitations/permission`).get()).data().status,'pending');await lifecycle.submitPermission(recipient,{...input,designatedFamilyEmails:['family@example.com']});});
test('concurrent permission approvals create one consent version and revoke stale invitations and entitlements',async()=>{const input={organizationId:'org',experienceId:'event',invitationId:'permission'};const ids=await Promise.all([lifecycle.approvePermission(staff,input),lifecycle.approvePermission(staff,input)]);assert.equal(ids[0],ids[1]);assert.equal((await db.doc(`${path}/participants/person`).get()).data().permissionVersion,2);assert.equal((await db.doc(`${path}/entitlements/song-entitlement`).get()).data().status,'revoked');assert.equal((await db.doc(`${path}/accessInvitations/access`).get()).data().status,'revoked');await assert.rejects(()=>lifecycle.purchase(recipient,{accessId:'access',productId:'digital'}),/no longer active/);});
test('post-experience purchases require matching current permissions and actual required material kinds',async()=>{await seedRecipient();const result=await lifecycle.purchase(recipient,{accessId:'access',productId:'digital'});assert.equal(result.request.organizationId,'org');assert.equal(result.request.priceCents,2000);assert.equal(result.request.status,'invoice_requested');assert.equal((await lifecycle.purchase(recipient,{accessId:'access',productId:'digital'})).request.id,result.request.id);await assert.rejects(()=>lifecycle.purchase(recipient,{accessId:'access',productId:'video'}),/requires a permitted/);await assert.rejects(()=>lifecycle.purchase(recipient,{accessId:'access',productId:'photos'}),/requires a permitted/);await db.doc(`${path}/entitlements/song-entitlement`).update({status:'revoked'});await assert.rejects(()=>lifecycle.purchase(recipient,{accessId:'access',productId:'digital'}),/permission|entitlement|released/i);});
test('creator media URLs cannot cross organization storage boundaries',async()=>{await seedRecipient();await db.doc('organizations/org/assets/song').update({storagePath:'organizations/other/private.mp3'});await assert.rejects(()=>lifecycle.media(staff,{organizationId:'org',assetId:'song'}),/file location/);});
test('Firestore rules deny browser financial writes and cross-tenant invoice reads',async()=>{const i=await issued();const own=environment.authenticatedContext('buyer',{email:'buyer@example.com',email_verified:true}).firestore(),other=environment.authenticatedContext('outsider').firestore(),admin=environment.authenticatedContext('staff').firestore();await assertSucceeds(getDoc(doc(own,`organizations/org/invoices/${i.id}`)));await assertFails(getDoc(doc(other,`organizations/org/invoices/${i.id}`)));await assertFails(updateDoc(doc(own,`organizations/org/invoices/${i.id}`),{status:'paid'}));await assertFails(updateDoc(doc(admin,`organizations/org/invoices/${i.id}`),{status:'paid'}));await assertFails(setDoc(doc(own,'organizations/org/experienceRequests/forged'),{organizationId:'org',amountCents:1,status:'converted'}));await assertFails(setDoc(doc(own,'users/buyer/purchaseRequests/forged'),{status:'paid'}));});

test('individual card payment is source-attributed, replay-safe and holds fulfillment after consent withdrawal',async()=>{
  const {makeIndividualPaymentService}=require('../individual-payments');await seedRecipient();
  await db.doc('postExperienceProducts/card-product').set({status:'active',audiences:['participant'],kind:'digital_song',name:'Sample digital keepsake',priceCents:3500});
  const {request}=await lifecycle.purchase(recipient,{accessId:'access',productId:'card-product'});
  let session;
  const stripe={checkout:{sessions:{create:async input=>(session={id:'cs_individual',url:'https://checkout.stripe.com/test',mode:'payment',status:'open',payment_status:'unpaid',currency:'usd',amount_total:3500,payment_intent:'pi_individual',metadata:input.metadata}),retrieve:async()=>session}}};
  const service=makeIndividualPaymentService(db,stripe,lifecycle);await service.checkout(recipient,{requestId:request.id});
  assert.equal((await db.doc(`users/person/purchaseRequests/${request.id}`).get()).data().status,'payment_pending');
  await db.doc(`${path}/participants/person/consents/consent`).update({state:'withdrawn'});
  session.status='complete';session.payment_status='paid';
  await service.webhook({id:'evt_individual',type:'checkout.session.completed',data:{object:session}});
  await service.webhook({id:'evt_individual',type:'checkout.session.completed',data:{object:session}});
  const paid=(await db.doc(`users/person/purchaseRequests/${request.id}`).get()).data();assert.equal(paid.status,'paid');assert.equal(paid.fulfillmentHold,true);assert.equal(paid.organizationId,'org');assert.equal(paid.experienceId,'event');
  assert.equal((await db.collection('users/person/purchaseReceipts').get()).size,1);
  assert.equal((await db.doc(`billingExceptions/purchase-${request.id}`).get()).data().status,'needs_review');
});
test('individual checkout revalidates the required asset kind after the request was created',async()=>{
  const {makeIndividualPaymentService}=require('../individual-payments');await seedRecipient();
  await db.doc('postExperienceProducts/changed-product').set({status:'active',audiences:['participant'],kind:'digital_song',name:'Changed product',priceCents:2000});
  const {request}=await lifecycle.purchase(recipient,{accessId:'access',productId:'changed-product'});
  await db.doc('postExperienceProducts/changed-product').update({kind:'event_video'});
  const service=makeIndividualPaymentService(db,{},lifecycle);await assert.rejects(()=>service.checkout(recipient,{requestId:request.id}),/materials required/);
});
test('manual fulfillment cannot trust a self-edited user email or bypass payment order',async()=>{
  await seedRecipient();const {request}=await lifecycle.purchase(recipient,{accessId:'access',productId:'digital'});
  const operations=makeLifecycleService(db,{getIdentity:async()=>({email:'different@example.com',emailVerified:true})});
  await assert.rejects(()=>operations.updatePurchase(staff,{userId:'person',requestId:request.id,status:'paid',reference:'test',confirmed:true}),/invitation/);
  const valid=makeLifecycleService(db,{getIdentity:async()=>({email:'person@example.com',emailVerified:true})});
  await assert.rejects(()=>valid.updatePurchase(staff,{userId:'person',requestId:request.id,status:'fulfilled'}),/requested state/);
});
test('release waits for verified bytes and current audience permission',async()=>{
  const {makeStorageIntegrity}=require('../storage-integrity');await seedRecipient();
  const ref=db.doc('organizations/org/assets/song');await ref.update({workflowStatus:'approved',mimeType:'audio/mpeg'});
  await db.doc('creatorAssignments/assignment').set({organizationId:'org',experienceId:'event',assignedUserId:'artist',status:'submitted'});
  await assert.rejects(()=>lifecycle.release(staff,{organizationId:'org',assetId:'song',audiences:['participant']}),/verify/);
  let stripped=false;const storage=makeStorageIntegrity(db,{file:()=>({getMetadata:async()=>[{size:'42',generation:'1',md5Hash:'sample-checksum',contentType:'audio/mpeg',metadata:{assignmentId:'assignment',submittedByUserId:'artist',firebaseStorageDownloadTokens:'old-token'}}],setMetadata:async m=>{stripped=m.metadata.firebaseStorageDownloadTokens===null;}})});
  await storage.verifyMaterial(staff,{organizationId:'org',assetId:'song'});assert.equal(stripped,true);
  await lifecycle.release(staff,{organizationId:'org',assetId:'song',audiences:['participant']});
  assert.equal((await ref.get()).data().workflowStatus,'released');
  assert.equal((await db.doc(`${path}/entitlements/song-entitlement`).get()).data().status,'revoked');
});
test('creators cannot approve, release or forge storage verification from a browser',async()=>{
  const creator=environment.authenticatedContext('artist').firestore();
  const target=doc(creator,'organizations/org/assets/song');
  await assertFails(updateDoc(target,{workflowStatus:'released',organizationVisible:true}));
  await assertFails(updateDoc(target,{storageVerifiedAt:new Date(),storageChecksum:'forged'}));
  await assert.rejects(()=>lifecycle.reviewDeliverable({uid:'artist'},{organizationId:'org',assetId:'song',decision:'approved'}),/staff/);
});
