"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useAuth } from "@/components/auth-provider";
import { SongKeepLockup } from "@/components/brand";
import { nativeAction } from "@/lib/firebase/native-services";
import { AuthorizedAsset } from "@/components/authorized-asset";
import type { CreatorAssignment, CreatorAssignmentRole, ExperienceAssetAudience, ExperienceParticipant, OrganizationAccount, OrganizationAsset, OrganizationAssetKind, OrganizationExperience, PlatformUserSummary } from "@/domain/organization-account";
import { createAdminCreatorAssignment, listAdminCreatorAssignments, listAdminCreatorSubmissions, listCreatorAssignments, listCreatorAssignmentSubmissions, listCreatorCandidates, releaseCreatorDeliverable, reviewCreatorDeliverable, submitCreatorDeliverable } from "@/lib/firebase/creator-deliverables";
import { listAdminOrganizations, listExperienceParticipants, listOrganizationExperiences } from "@/lib/firebase/organization-account";
import styles from "./invoice-surface.module.css";
const val = (data: FormData, name: string) => String(data.get(name) ?? "");
export function CreatorDeliverySurface({ admin = false }: { admin?: boolean }) {
  const { user, status } = useAuth();
  const [assignments, setAssignments] = useState<CreatorAssignment[]>([]);
  const [assets, setAssets] = useState<OrganizationAsset[]>([]);
  const [organizations, setOrganizations] = useState<OrganizationAccount[]>([]);
  const [people, setPeople] = useState<PlatformUserSummary[]>([]);
  const [experiences, setExperiences] = useState<OrganizationExperience[]>([]);
  const [participants, setParticipants] = useState<ExperienceParticipant[]>([]);
  const [organizationId, setOrganizationId] = useState("");
  const [experienceId, setExperienceId] = useState("");
  const [selectedId, setSelectedId] = useState("");
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState<number | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const selected = assignments.find(item => item.id === selectedId);
  const load = useCallback(async () => {
    if (!user) return;
    const next = admin ? await listAdminCreatorAssignments() : await listCreatorAssignments(user.uid);
    setAssignments(next); if (!selectedId && next[0]) setSelectedId(next[0].id);
    if (admin) { setOrganizations(await listAdminOrganizations()); setPeople(await listCreatorCandidates()); }
    const assignment = next.find(item => item.id === selectedId) ?? next[0];
    if (assignment) setAssets(admin ? await listAdminCreatorSubmissions(assignment.organizationId, assignment.experienceId).then(items => items.filter(item => item.assignmentId === assignment.id)) : await listCreatorAssignmentSubmissions(assignment));
  }, [admin, selectedId, user]);
  useEffect(() => { load().catch(reason => setError(reason.message)); }, [load]);
  useEffect(() => { if (!organizationId) return; listOrganizationExperiences(organizationId).then(setExperiences).catch(reason => setError(reason.message)); }, [organizationId]);
  useEffect(() => { if (!organizationId || !experienceId) { setParticipants([]); return; } listExperienceParticipants(organizationId, experienceId).then(setParticipants).catch(reason => setError(reason.message)); }, [organizationId, experienceId]);
  async function run(work: () => Promise<unknown>, message: string) { setBusy(true); setError(""); setNotice(""); try { await work(); await load(); setNotice(message); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to complete this action."); } finally { setBusy(false); setProgress(null); } }
  async function assign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget),person=people.find(item=>item.userId===val(data,"creator")),org=organizations.find(item=>item.id===organizationId),experience=experiences.find(item=>item.id===experienceId),participant=participants.find(item=>item.id===val(data,"participant")); if (!person || !org || !experience || !user) return;
    await run(() => createAdminCreatorAssignment({assignedUser:person,organizationId:org.id,organizationName:org.name,experienceId:experience.id,experienceTitle:experience.title,participantId:participant?.id,participantName:participant?.displayName,role:val(data,"role") as CreatorAssignmentRole,dueAt:val(data,"dueAt")||undefined,createdByUserId:user.uid}), "Assignment saved. The creator can now submit materials privately.");
  }
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget),file=data.get("file"); if (!selected || !user || !(file instanceof File) || !file.size) return;
    await run(() => submitCreatorDeliverable({assignment:selected,userId:user.uid,userName:user.displayName??user.email??"Creator",title:val(data,"title"),kind:val(data,"kind") as OrganizationAssetKind,notes:val(data,"notes"),file,onProgress:setProgress}), "Submitted for review. The organization and family cannot access it until SongKeep approves and releases it.");
  }
  if (status === "loading") return <main className={styles.shell}><p role="status">Opening Creator Studio…</p></main>;
  if (!user) return <main className={styles.shell}><h1>Creator Studio</h1><p>Sign in to open your assignments.</p><Link className={styles.primary} href="/login?next=%2Fcreator%2Fdeliverables">Sign in</Link></main>;
  return <main className={styles.shell}><header className={styles.header}><Link href={admin?"/admin":"/creator/work"}>← {admin?"Operations":"Creator Studio"}</Link><SongKeepLockup variant="app" /></header><div className={styles.heading}><div><p className={styles.eyebrow}>{admin?"SongKeep review":"Your creative work"}</p><h1>{admin?"Review & release":"Your assignments"}</h1><p>Private submissions. Clear feedback. A deliberate release.</p></div><button onClick={()=>run(load,"Updated.")} disabled={busy}>Refresh</button></div>
    {error?<p className={styles.error} role="alert">{error}</p>:null}{notice?<p className={styles.notice} role="status">{notice}</p>:null}
    {admin?<details><summary>Assign creative work</summary><form className={styles.form} onSubmit={assign}><label>Organization<select required value={organizationId} onChange={event=>{setOrganizationId(event.target.value);setExperienceId("");}}><option value="">Choose organization</option>{organizations.map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</select></label><label>Experience<select required value={experienceId} onChange={event=>setExperienceId(event.target.value)}><option value="">Choose experience</option>{experiences.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Participant<select name="participant"><option value="">Group / whole experience</option>{participants.map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Creator<select required name="creator"><option value="">Choose account</option>{people.map(person=><option key={person.userId} value={person.userId}>{person.displayName} · {person.email}</option>)}</select></label><label>Role<select name="role"><option value="songwriter">Songwriter</option><option value="interviewer">Interviewer</option><option value="artist">Artist</option><option value="producer">Producer</option></select></label><label>Due date<input type="date" name="dueAt" /></label><button type="submit" disabled={busy}>Create assignment</button></form></details>:null}
    <div className={styles.layout}><nav className={styles.list} aria-label="Creative assignments">{assignments.map(item=><button key={item.id} aria-current={selectedId===item.id?"page":undefined} onClick={()=>setSelectedId(item.id)}><strong>{item.experienceTitle}</strong><span>{item.organizationName}</span><span>{item.participantName??"Group materials"} · {item.role}</span><span>{item.status.replaceAll("_"," ")}</span></button>)}{!assignments.length?<p>No assignments yet.</p>:null}</nav><section className={styles.detail}>
    {selected?<><h2>{selected.experienceTitle}</h2><p>{selected.organizationName} · {selected.participantName??"Group materials"}</p>{!admin?<form className={styles.form} onSubmit={upload}><label>Material title<input required name="title" maxLength={160} /></label><label>Type<select name="kind"><option value="song">Song / recording</option><option value="lyrics">Lyrics</option><option value="event_video">Event video</option><option value="photo">Photo</option><option value="album_artwork">Album artwork</option><option value="other">Other working material</option></select></label><label>File<input required type="file" name="file" accept="audio/*,video/*,image/jpeg,image/png,image/webp,application/pdf,text/plain,.doc,.docx" /></label><label>Notes<textarea name="notes" rows={3} /></label><p>Files remain private until reviewed and released. Each submission keeps its own record; an upload never overwrites a previous submission.</p><button className={styles.primary} type="submit" disabled={busy||selected.status==="cancelled"}>Submit for review</button>{progress!==null?<><progress max={100} value={progress} aria-label="Upload progress" /><p role="status">{Math.round(progress)}% uploaded</p></>:null}</form>:null}
    {assets.map(asset=><article key={asset.id}><div className={styles.line}><div><h3>{asset.title}</h3><p>{asset.workflowStatus?.replaceAll("_"," ")??asset.status} · {asset.fileName}</p></div><div><AuthorizedAsset organizationId={asset.organizationId} assetId={asset.id} kind={asset.kind} />{admin ? <button disabled={busy} onClick={() => run(() => nativeAction("verifyMaterial", { organizationId: asset.organizationId, assetId: asset.id }), "Upload checked and protected. Approved materials may now be released.")}>Check upload</button> : null}</div></div>{asset.reviewNotes?<p>Review: {asset.reviewNotes}</p>:null}
      {admin&&["submitted","approved","changes_requested","rejected"].includes(asset.workflowStatus??"")?<form className={styles.form} onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(()=>reviewCreatorDeliverable({organizationId:asset.organizationId,assetId:asset.id,reviewedByUserId:user.uid,decision:val(data,"decision") as "approved"|"changes_requested"|"rejected",reviewNotes:val(data,"notes")}),"Review saved. Approval does not yet release the material.");}}><label>Review decision<select name="decision"><option value="approved">Approve</option><option value="changes_requested">Request changes</option><option value="rejected">Reject</option></select></label><label>Feedback<textarea name="notes" /></label><button type="submit" disabled={busy}>Save review</button></form>:null}
      {admin&&asset.workflowStatus==="approved"?<form className={styles.form} onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void run(()=>releaseCreatorDeliverable({organizationId:asset.organizationId,experienceId:asset.experienceId,assetId:asset.id,participantId:asset.participantId,audiences:data.getAll("audiences").map(String) as ExperienceAssetAudience[],reviewedByUserId:user.uid,rightsNote:val(data,"rightsNote")}),"Released to the selected audiences after a current permission check.");}}><fieldset><legend>Release audience</legend>{["organization","participant","designated_family"].map(audience=><label className={styles.check} key={audience}><input type="checkbox" name="audiences" value={audience} />{audience.replaceAll("_"," ")}</label>)}</fieldset><label>Permission review note<textarea name="rightsNote" required={!asset.participantId} /></label><p>Current consent must permit every selected audience. Group materials require a documented review. Public marketing is not enabled by this action.</p><button className={styles.primary} type="submit" disabled={busy}>Release approved material</button></form>:null}
    </article>)}</>:null}</section></div></main>;
}
